language: cpp
compiler: gcc
os: linux


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

stages:
  - test

before_script:
  - export CC=gcc-5
  - export CXX=g++-5

jobs:
  include:
  - stage: test
    name: "make"
    script:
      - make clean
      - make
      - make tar
  - name: "cmake"
    script:
      - cmake .
      - cmake --build .
  - name: "cppcheck"
    install:
      - sudo apt-get install -qq cppcheck
    script:
      - cppcheck --error-exitcode=1 .
