language: cpp
compiler: gcc
os: linux

env:
  global:
    - CXX=g++-7
    - CC=gcc-7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

stages:
  - test

jobs:
  include:
  - stage: test
    name: "make"
    script:
      - make clean
      - make
      - make tar
  - name: "cmake"
    script:
      - cmake .
      - cmake --build .

