language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_script:
- export CC=gcc-7
- export CXX=g++-7

jobs:
  include:
  - stage: test
    name: "make"
    - make clean
    - make
    - make tar
    script:
  - name: "cmake"
    script:
    - cmake .
    - cmake --build .

